// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Content       string             `json:"content"`
	Excerpt       *string            `json:"excerpt"`
	Author        *string            `json:"author"`
	CoverImageUrl *string            `json:"cover_image_url"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	IsPublished   *bool              `json:"is_published"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Band struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Bio         *string            `json:"bio"`
	Hometown    *string            `json:"hometown"`
	ImageUrl    *string            `json:"image_url"`
	Website     *string            `json:"website"`
	SpotifyUrl  *string            `json:"spotify_url"`
	Instagram   *string            `json:"instagram"`
	Facebook    *string            `json:"facebook"`
	BandcampUrl *string            `json:"bandcamp_url"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BandGenre struct {
	BandID    int32              `json:"band_id"`
	GenreID   int32              `json:"genre_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Genre struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Show struct {
	ID             int32              `json:"id"`
	VenueID        int32              `json:"venue_id"`
	Title          *string            `json:"title"`
	Description    *string            `json:"description"`
	ImageUrl       *string            `json:"image_url"`
	Date           pgtype.Timestamptz `json:"date"`
	DoorsTime      pgtype.Time        `json:"doors_time"`
	ShowTime       pgtype.Time        `json:"show_time"`
	PriceMin       pgtype.Numeric     `json:"price_min"`
	PriceMax       pgtype.Numeric     `json:"price_max"`
	TicketUrl      *string            `json:"ticket_url"`
	AgeRestriction *string            `json:"age_restriction"`
	Status         *string            `json:"status"`
	Source         *string            `json:"source"`
	ScrapedData    []byte             `json:"scraped_data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ShowBand struct {
	ShowID           int32              `json:"show_id"`
	BandID           int32              `json:"band_id"`
	IsHeadliner      *bool              `json:"is_headliner"`
	PerformanceOrder *int32             `json:"performance_order"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Venue struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Address   *string            `json:"address"`
	City      *string            `json:"city"`
	State     *string            `json:"state"`
	ZipCode   *string            `json:"zip_code"`
	Region    *string            `json:"region"`
	Latitude  pgtype.Numeric     `json:"latitude"`
	Longitude pgtype.Numeric     `json:"longitude"`
	Capacity  *int32             `json:"capacity"`
	Website   *string            `json:"website"`
	Phone     *string            `json:"phone"`
	ImageUrl  *string            `json:"image_url"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type VenueScraper struct {
	ID            int32              `json:"id"`
	VenueID       int32              `json:"venue_id"`
	Url           string             `json:"url"`
	ScraperType   string             `json:"scraper_type"`
	Selectors     json.RawMessage    `json:"selectors"`
	DateFormat    *string            `json:"date_format"`
	IsActive      *bool              `json:"is_active"`
	LastScrapedAt pgtype.Timestamptz `json:"last_scraped_at"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	ErrorCount    *int32             `json:"error_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
