// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Add a genre to a band
	AddBandGenre(ctx context.Context, arg AddBandGenreParams) error
	// Check if band exists by slug
	BandExists(ctx context.Context, slug string) (bool, error)
	// Count bands by genre (for pagination)
	CountBandsByGenre(ctx context.Context, dollar_1 []string) (int64, error)
	// Count bands in a genre (for pagination)
	CountBandsInGenre(ctx context.Context, genreID int32) (int64, error)
	// Count upcoming shows by genre (for genre filter)
	CountShowsByGenre(ctx context.Context, dollar_1 []string) (int64, error)
	// Create a new band
	CreateBand(ctx context.Context, arg CreateBandParams) (CreateBandRow, error)
	// Create a new band with all fields
	CreateBandFull(ctx context.Context, arg CreateBandFullParams) (Band, error)
	// Create a new show (band submission)
	CreateShow(ctx context.Context, arg CreateShowParams) (CreateShowRow, error)
	// Link a band to a show
	CreateShowBand(ctx context.Context, arg CreateShowBandParams) error
	// Check if genre exists by ID
	GenreExists(ctx context.Context, id int32) (bool, error)
	// Check if genre exists by slug
	GenreExistsBySlug(ctx context.Context, slug string) (bool, error)
	// ============================================
	// BANDS QUERIES
	// ============================================
	// Get band by ID
	GetBand(ctx context.Context, id int32) (Band, error)
	// Get band by name (case-insensitive) for matching during submissions
	GetBandByName(ctx context.Context, lower string) (Band, error)
	// Get band by slug for detail page
	GetBandBySlug(ctx context.Context, slug string) (Band, error)
	// Get genres for a band
	GetBandGenres(ctx context.Context, bandID int32) ([]GetBandGenresRow, error)
	// Get genres for multiple bands (batch load)
	GetBandGenresBatch(ctx context.Context, dollar_1 []int32) ([]GetBandGenresBatchRow, error)
	// Get genres for a band (used when fetching show details)
	GetBandGenresForShow(ctx context.Context, bandID int32) ([]GetBandGenresForShowRow, error)
	// Get upcoming shows for a band
	GetBandUpcomingShows(ctx context.Context, bandID int32) ([]GetBandUpcomingShowsRow, error)
	// Get bands for a specific genre (for genre detail page)
	GetBandsByGenre(ctx context.Context, arg GetBandsByGenreParams) ([]GetBandsByGenreRow, error)
	// ============================================
	// GENRES QUERIES
	// ============================================
	// Get genre by ID
	GetGenre(ctx context.Context, id int32) (Genre, error)
	// Get genre by slug
	GetGenreBySlug(ctx context.Context, slug string) (Genre, error)
	// Get all bands for a show with their genres
	GetShowBands(ctx context.Context, showID int32) ([]GetShowBandsRow, error)
	// Get bands for shows at a venue (batch load for venue detail)
	GetShowBandsForVenue(ctx context.Context, dollar_1 []int32) ([]GetShowBandsForVenueRow, error)
	// ============================================
	// SHOWS QUERIES
	// ============================================
	// Get single show with venue info
	GetShowByID(ctx context.Context, id int32) (GetShowByIDRow, error)
	// Find bands with shared genres (similar bands)
	// Excludes the source band and orders by number of shared genres
	GetSimilarBands(ctx context.Context, arg GetSimilarBandsParams) ([]GetSimilarBandsRow, error)
	// Find similar bands with their shared genre names
	GetSimilarBandsWithGenres(ctx context.Context, arg GetSimilarBandsWithGenresParams) ([]GetSimilarBandsWithGenresRow, error)
	// ============================================
	// VENUES QUERIES
	// ============================================
	// Get venue by ID
	GetVenue(ctx context.Context, id int32) (Venue, error)
	// Get venue by slug for detail page
	GetVenueBySlug(ctx context.Context, slug string) (Venue, error)
	// Get upcoming shows for a venue (for venue detail page)
	GetVenueUpcomingShows(ctx context.Context, arg GetVenueUpcomingShowsParams) ([]GetVenueUpcomingShowsRow, error)
	// Search bands only (for search endpoint's bands section)
	GlobalSearchBands(ctx context.Context, arg GlobalSearchBandsParams) ([]GlobalSearchBandsRow, error)
	// Search shows only (for search endpoint's shows section)
	GlobalSearchShows(ctx context.Context, arg GlobalSearchShowsParams) ([]GlobalSearchShowsRow, error)
	// Search venues only (for search endpoint's venues section)
	GlobalSearchVenues(ctx context.Context, arg GlobalSearchVenuesParams) ([]GlobalSearchVenuesRow, error)
	// List bands with pagination
	ListBands(ctx context.Context, arg ListBandsParams) ([]ListBandsRow, error)
	// List bands filtered by genre slug(s) with pagination
	ListBandsByGenre(ctx context.Context, arg ListBandsByGenreParams) ([]ListBandsByGenreRow, error)
	// Shows that are free (price_min is NULL or 0)
	ListFreeShows(ctx context.Context, arg ListFreeShowsParams) ([]ListFreeShowsRow, error)
	// List all genres ordered by name
	ListGenres(ctx context.Context) ([]Genre, error)
	// List genres with count of bands
	ListGenresWithBandCount(ctx context.Context) ([]ListGenresWithBandCountRow, error)
	// List genres with count of upcoming shows
	ListGenresWithShowCount(ctx context.Context) ([]ListGenresWithShowCountRow, error)
	// Filter shows by date range (inclusive)
	ListShowsByDateRange(ctx context.Context, arg ListShowsByDateRangeParams) ([]ListShowsByDateRangeRow, error)
	// Filter shows by genre slug(s) - shows with bands matching any of the genres
	ListShowsByGenre(ctx context.Context, arg ListShowsByGenreParams) ([]ListShowsByGenreRow, error)
	// Filter shows by price range
	ListShowsByPriceRange(ctx context.Context, arg ListShowsByPriceRangeParams) ([]ListShowsByPriceRangeRow, error)
	// Filter shows by region(s)
	ListShowsByRegion(ctx context.Context, arg ListShowsByRegionParams) ([]ListShowsByRegionRow, error)
	// Filter shows by venue slug(s)
	ListShowsByVenue(ctx context.Context, arg ListShowsByVenueParams) ([]ListShowsByVenueRow, error)
	// Shows happening Friday-Sunday of current or next weekend
	ListShowsThisWeekend(ctx context.Context) ([]ListShowsThisWeekendRow, error)
	// Shows happening today
	ListShowsTonight(ctx context.Context) ([]ListShowsTonightRow, error)
	// List upcoming scheduled shows with pagination
	// Used for homepage and general show listing
	ListUpcomingShows(ctx context.Context, arg ListUpcomingShowsParams) ([]ListUpcomingShowsRow, error)
	// List all venues ordered by name
	ListVenues(ctx context.Context) ([]Venue, error)
	// List venues filtered by region(s)
	ListVenuesByRegion(ctx context.Context, dollar_1 []string) ([]ListVenuesByRegionRow, error)
	// List venues with count of upcoming scheduled shows
	ListVenuesWithShowCount(ctx context.Context) ([]ListVenuesWithShowCountRow, error)
	// ============================================
	// GLOBAL SEARCH QUERIES
	// ============================================
	// Unified search across shows, bands, and venues
	// Returns results with a type discriminator
	// Note: This uses UNION ALL for efficiency (no deduplication needed)
	SearchAll(ctx context.Context, arg SearchAllParams) ([]SearchAllRow, error)
	// Full-text search on band name and bio
	SearchBands(ctx context.Context, arg SearchBandsParams) ([]SearchBandsRow, error)
	// Simple search returning minimal fields (for global search)
	SearchBandsSimple(ctx context.Context, arg SearchBandsSimpleParams) ([]SearchBandsSimpleRow, error)
	// Full-text search on show titles
	SearchShows(ctx context.Context, arg SearchShowsParams) ([]SearchShowsRow, error)
	// Search shows including band names in the search
	// This finds shows where either the title OR any band name matches
	SearchShowsWithBands(ctx context.Context, arg SearchShowsWithBandsParams) ([]SearchShowsWithBandsRow, error)
	// Full-text search on venue names
	SearchVenues(ctx context.Context, arg SearchVenuesParams) ([]SearchVenuesRow, error)
	// Check if venue exists by ID (for validation)
	VenueExists(ctx context.Context, id int32) (bool, error)
}

var _ Querier = (*Queries)(nil)
